=== Apress/Crafting-Great-APIs-with-Domain-Driven-Design/chapter-6-2/book.schema.json
{
  "$id": "https://example.com/book",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Book",
  "description": "A schema representing a book and its metadata for the library for, e.g., search results",
  "type": "object",
  "properties": {
    "isbn13": {
      "type": "string",
      "pattern": "^[0-9]{13}$",
      "description": "The 13-digit ISBN"
    },
    "title": {
      "type": "string",
      "minLength": 1,
      "maxLength": 200,
      "description": "The title of the book"
    },
    "coverThumbnailWebP": {
      "type": "string",
      "contentEncoding": "base64",
      "contentMediaType": "image/webp",
      "description": "Base64 encoded WebP image of the book cover thumbnail"
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "minLength": 1,
            "maxLength": 100,
            "examples": [
              "Eric Evans",
              "Dr. John Smith"
            ],
            "description": "The full name of the author with titles"
          },
          "portraitThumbnailWebP": {
            "type": "string",
            "contentEncoding": "base64",
            "contentMediaType": "image/webp",
            "description": "Base64 encoded WebP image of the author's portrait thumbnail"
          }
        },
        "required": [
          "name"
        ]
      },
      "minItems": 1,
      "uniqueItems": true,
      "description": "List of authors of the book"
    },
    "numberOfTextPosition": {
      "type": "integer",
      "minimum": 0,
      "description": "The number of text position in the book"
    },
    "category": {
      "type": "string",
      "enum": ["NON_FICTION", "FICTION"],
      "description": "The main category of the book"
    },
    "tags": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 50
      },
      "uniqueItems": true,
      "maxItems": 20,
      "description": "List of tags associated with the book (top 20)"
    },
    "rating": {
      "type": "number",
      "minimum": 0,
      "maximum": 5,
      "multipleOf" : 0.1,
      "description": "The average rating of the book (0 to 5 stars, with one decimal place)"
    },
    "hasValidLicense": {
      "type": "boolean",
      "description": "Indicates whether the library has a valid license for the book at the moment"
    },
    "publishingDate": {
      "type": "string",
      "format": "date",
      "description": "The date when the book was published",
      "examples": ["2000-01-01"]
    }
  },
  "required": [
    "isbn13",
    "title",
    "authors",
    "numberOfTextPosition",
    "category",
    "tags",
    "hasValidLicense",
    "publishingDate"
  ],
  "additionalProperties": false
}

=== Apress/Crafting-Great-APIs-with-Domain-Driven-Design/chapter-6-2/book.json
{
    "isbn13": "9783161484100",
    "title": "The best book",
    "coverThumbnailWebP": "aW1hZ2UgaW4gYmFzZTY0",
    "authors": [
        {
            "name": "author 1",
            "portraitThumbnailWebP": "aW1hZ2UgaW4gYmFzZTY0"
        },
        {
            "name": "author 2"
        }
    ],
    "numberOfTextPosition": 0,
    "category": "NON_FICTION",
    "tags": ["DDD", "Modeling"],
    "rating": 4.5,
    "hasValidLicense": true,
    "publishingDate": "2020-08-01"
}
