=== Apress/Crafting-Great-APIs-with-Domain-Driven-Design/chapter-6-2/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation>
      A schema representing a book and its metadata for the library for, e.g., search results
    </xs:documentation>
  </xs:annotation>

  <xs:element name="book" type="BookType"/>

  <xs:complexType name="BookType">
    <xs:sequence>
      <xs:element name="title" type="TitleType"/>
      <xs:element name="coverThumbnailWebP" type="xs:base64Binary" minOccurs="0" maxOccurs="1"/>
      <xs:element name="authors" type="AuthorsType"/>
      <xs:element name="numberOfTextPosition" type="NonNegativeIntegerType"/>
      <xs:element name="category" type="CategoryType"/>
      <xs:element name="tags" type="TagsType"/>
      <xs:element name="rating" type="RatingType" minOccurs="0" maxOccurs="1"/>
      <xs:element name="hasValidLicense" type="xs:boolean"/>
      <xs:element name="publishingDate" type="xs:date"/>
    </xs:sequence>
    <xs:attribute name="isbn13" type="ISBN13Type" use="required"/>
  </xs:complexType>

  <xs:simpleType name="ISBN13Type">
    <xs:annotation>
      <xs:documentation>13-digit International Standard Book Number</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{13}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TitleType">
    <xs:annotation>
      <xs:documentation>The title of the book</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="200"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="AuthorsType">
    <xs:sequence>
      <xs:element name="author" type="AuthorType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="AuthorType">
    <xs:sequence>
      <xs:element name="name" type="AuthorNameType"/>
      <xs:element name="portraitThumbnailWebP" type="xs:base64Binary" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="AuthorNameType">
    <xs:annotation>
      <xs:documentation>The full name of the author with titles, e.g., "Eric Evans", "Dr. John Smith"</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="100"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NonNegativeIntegerType">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CategoryType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NON_FICTION"/>
      <xs:enumeration value="FICTION"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="TagsType">
    <xs:sequence>
      <xs:element name="tag" type="TagType" minOccurs="0" maxOccurs="20"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="TagType">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
      <xs:maxLength value="50"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="RatingType">
    <xs:restriction base="xs:decimal">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="5"/>
      <xs:fractionDigits value="1"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== Apress/Crafting-Great-APIs-with-Domain-Driven-Design/chapter-6-2/book.xml
<?xml version="1.0" encoding="utf-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="book.xsd"
   isbn13="9783161484100">
   <title>The best book</title>
   <coverThumbnailWebP>aW1hZ2UgaW4gYmFzZTY0</coverThumbnailWebP>
   <authors>
      <author>
         <name>author 1</name>
         <portraitThumbnailWebP>aW1hZ2UgaW4gYmFzZTY0</portraitThumbnailWebP>
      </author>
      <author>
         <name>author 2</name>
      </author>
   </authors>
   <numberOfTextPosition>4</numberOfTextPosition>
   <category>NON_FICTION</category>
   <tags>
      <tag>DDD</tag>
      <tag>Modeling</tag>
   </tags>
   <rating>4.5</rating>
   <hasValidLicense>true</hasValidLicense>
   <publishingDate>2020-08-01</publishingDate>
</book>
